### PR TITLE
Reorganized code with Elijah's manually merged

### PR DESCRIPTION
**Pull request by rizend**

### CODE REVIEW

**Comment by rmendez23** [comment]
Looks like we have some conflicts in the server file?

**Comment by rizend** [comment]
I have a new file named `Server.py` that has the functionality that was in `server_pi2.py`, so I think the conflict is that there is a newer version of `server_pi2.py` (with Elijah's stuff) but I actually already manually added all the stuff in the newer version of `server_pi2.py` to `Server.py`.

**Comment by rmendez23** [comment]
Confused... server_pi2.py was deleted on your branch if I'm understanding your commits?

**Comment by rizend** [comment]
Yes, I looked at the changes Elijah made on the master branch to `server_pi2.py` and incorporated them into `Server.py`; to resolve it, I think you just need to tell github your okay with `server_pi2.py` being deleted on master.

**Comment by rmendez23** [comment]
Ah ok, I'll see what I can do. I think it needs me to use command line to resolve it so pardon the delay as I figure out how to do that.

**Pull request merged**
